#!usr/bin/env bash

# general path variables
export EDITOR="nvim"
export REPOS="$HOME/repositories"
export DATA="$HOME/data"

export CONF_FILES="$HOME/.config"

export SH_CONF="$CONF_FILES/shell_scripts"
export STARSHIP_CONFIG="$CONF_FILES/starship/config.toml"

export TMP_DATA="$REPOS/tmp"

export IPYTHONDIR="$CONF_FILES/ipython"

export TERM="screen-256color"

# calling general bash scripts 
for file in "$CONF_FILES/shell_scripts/*.sh"
do
    eval "$(cat $file)"
done

# starship
eval "$(starship init bash)"

# shared history
shopt -s histappend
PROMPT_COMMAND="${PROMPT_COMMAND:+$PROMPT_COMMAND$'\n'}history -a; history -c; history -r"

# vi mode
set -o vi

# fzf
[[ -d "/usr/share/fzf/" ]] && source "/usr/share/fzf/key-bindings.bash"
[[ -d "/usr/share/doc/fzf" ]] && source "/usr/share/doc/fzf/examples/key-bindings.bash"

# zoxide
eval "$(zoxide init bash)"
